<?php
$Array_Mod_Lang["txt:Detail Head"]["TH"] = "ระบบจัดการ Content";
$Array_Mod_Lang["txt:Detail Head"]["EN"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["CN"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["JP"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["DE"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["FR"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["ES"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["KR"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["AED"] = "Manage Content system";

$Array_Mod_Lang["txt:Head 01"]["TH"] = "วันที่แสดงผล";
$Array_Mod_Lang["txt:Head 01"]["EN"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["CN"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["JP"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["DE"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["FR"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["ES"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["KR"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["AED"] = "Content Date";
$Array_Mod_Lang["txt:Head 02"]["TH"] = "รายละเอียด";
$Array_Mod_Lang["txt:Head 02"]["EN"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["CN"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["JP"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["DE"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["FR"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["ES"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["KR"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["AED"] = "Content Information";
$Array_Mod_Lang["txt:Head 03"]["TH"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["EN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["CN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["JP"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["DE"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["FR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["ES"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["KR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 03"]["AED"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["TH"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["EN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["CN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["JP"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["DE"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["FR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["ES"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["KR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["AED"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["TH"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["EN"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["CN"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["JP"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["DE"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["FR"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["ES"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["KR"] = "Content Setting";
$Array_Mod_Lang["txt:Head 05"]["AED"] = "Content Setting";
$Array_Mod_Lang["txt:Head 06"]["TH"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["EN"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["CN"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["JP"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["DE"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["FR"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["ES"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["KR"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 06"]["AED"] = "Content Relate Link";
$Array_Mod_Lang["txt:Head 07"]["TH"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["EN"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["CN"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["JP"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["DE"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["FR"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["ES"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["KR"] = "Content Comment";
$Array_Mod_Lang["txt:Head 07"]["AED"] = "Content Comment";
$Array_Mod_Lang["txt:Head 08"]["TH"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["EN"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["CN"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["JP"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["DE"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["FR"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["ES"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["KR"] = "Content Rating";
$Array_Mod_Lang["txt:Head 08"]["AED"] = "Content Rating";

$Array_Mod_Lang["txtinput:inputDateTime"]["TH"] = "ระยะเวลาการแสดงผล";//Header ( พาดหัวหลัก )
$Array_Mod_Lang["txtinput:inputDateTime"]["EN"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["CN"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["JP"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["DE"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["FR"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["ES"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["KR"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDateTime"]["AED"] = "Expire Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["TH"] = "วันที่เผยแพร่";
$Array_Mod_Lang["txtinput:inputDesDate"]["EN"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["CN"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["JP"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["DE"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["FR"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["ES"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["KR"] = "Des Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["AED"] = "Des Date";

$Array_Mod_Lang["txt:Group Head 01"]["TH"] = "กิจกรรม";
$Array_Mod_Lang["txt:Group Head 01"]["EN"] = "กิจกรรม";

$Array_Mod_Lang["txtinput:inputSubject"]["TH"] = "พาดหัว";//Header ( พาดหัวหลัก )
$Array_Mod_Lang["txtinput:inputSubject"]["EN"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["CN"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["JP"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["DE"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["FR"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["ES"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["KR"] = "Header";
$Array_Mod_Lang["txtinput:inputSubject"]["AED"] = "Header";
$Array_Mod_Lang["txtinput:inputTitle"]["TH"] = "รายละเอียดย่อ";
$Array_Mod_Lang["txtinput:inputTitle"]["EN"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["CN"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["JP"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["DE"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["FR"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["ES"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["KR"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["AED"] = "Title";
$Array_Mod_Lang["txtinput:inputDetail"]["TH"] = "รายละเอียด";
$Array_Mod_Lang["txtinput:inputDetail"]["EN"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["CN"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["JP"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["DE"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["FR"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["ES"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["KR"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["AED"] = "Detail";
$Array_Mod_Lang["txtinput:inputGroup"]["TH"] = "กลุ่ม";
$Array_Mod_Lang["txtinput:inputGroup"]["EN"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["CN"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["JP"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["DE"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["FR"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["ES"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["KR"] = "Group";
$Array_Mod_Lang["txtinput:inputGroup"]["AED"] = "Group";

$Array_Mod_Lang["txtinput:inputBy"]["TH"] = "เขียนโดย";//Header ( พาดหัวหลัก )
$Array_Mod_Lang["txtinput:inputBy"]["EN"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["CN"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["JP"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["DE"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["FR"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["ES"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["KR"] = "By";
$Array_Mod_Lang["txtinput:inputBy"]["AED"] = "By";

$Array_Mod_Lang["txtinput:OnOffStatus"]["TH"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["EN"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["CN"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["JP"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["DE"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["FR"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["ES"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["KR"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffStatus"]["AED"] = "ปิด / เปิด การแสดงผลหลัก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["TH"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["EN"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["CN"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["JP"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["DE"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["FR"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["ES"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["KR"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffHomeStatus"]["AED"] = "ปิด / เปิด การแสดงผลหน้าแรก";
$Array_Mod_Lang["txtinput:OnOffRating"]["TH"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["EN"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["CN"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["JP"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["DE"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["FR"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["ES"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["KR"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffRating"]["AED"] = "ปิด / เปิด การแสดงผลค่าความนิยม";
$Array_Mod_Lang["txtinput:OnOffComment"]["TH"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["EN"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["CN"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["JP"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["DE"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["FR"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["ES"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["KR"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffComment"]["AED"] = "ปิด / เปิด การแสดงความคิดเห็น";
$Array_Mod_Lang["txtinput:OnOffRelate"]["TH"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["EN"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["CN"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["JP"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["DE"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["FR"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["ES"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["KR"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffRelate"]["AED"] = "ปิด / เปิด การแสดงเนื้อหาเกี่ยวข้อง";
$Array_Mod_Lang["txtinput:OnOffPin"]["TH"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["EN"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["CN"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["JP"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["DE"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["FR"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["ES"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["KR"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPin"]["AED"] = "ปิด / เปิด ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txtinput:OnOffPassword"]["TH"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["EN"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["CN"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["JP"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["DE"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["FR"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["ES"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["KR"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPassword"]["AED"] = "ปิด / เปิด รหัสผ่าน";
$Array_Mod_Lang["txtinput:OnOffPublic"]["TH"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["EN"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["CN"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["JP"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["DE"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["FR"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["ES"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["KR"] = "ปิด / เปิด Public";
$Array_Mod_Lang["txtinput:OnOffPublic"]["AED"] = "ปิด / เปิด Public";

$Array_Mod_Lang["txt:HomeStatus"]["TH"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["EN"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["CN"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["JP"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["DE"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["FR"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["ES"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["KR"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["AED"] = "หน้าแรก";
$Array_Mod_Lang["txt:Rating"]["TH"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["EN"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["CN"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["JP"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["DE"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["FR"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["ES"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["KR"] = "ความนิยม";
$Array_Mod_Lang["txt:Rating"]["AED"] = "ความนิยม";
$Array_Mod_Lang["txt:Comment"]["TH"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["EN"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["CN"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["JP"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["DE"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["FR"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["ES"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["KR"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Comment"]["AED"] = "ความคิดเห็น";
$Array_Mod_Lang["txt:Pin"]["TH"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["EN"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["CN"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["JP"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["DE"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["FR"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["ES"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["KR"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["AED"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Password"]["TH"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["EN"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["CN"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["JP"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["DE"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["FR"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["ES"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["KR"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Password"]["AED"] = "รหัสผ่าน";
$Array_Mod_Lang["txt:Public"]["TH"] = "Public";
$Array_Mod_Lang["txt:Public"]["EN"] = "Public";
$Array_Mod_Lang["txt:Public"]["CN"] = "Public";
$Array_Mod_Lang["txt:Public"]["JP"] = "Public";
$Array_Mod_Lang["txt:Public"]["DE"] = "Public";
$Array_Mod_Lang["txt:Public"]["FR"] = "Public";
$Array_Mod_Lang["txt:Public"]["ES"] = "Public";
$Array_Mod_Lang["txt:Public"]["KR"] = "Public";
$Array_Mod_Lang["txt:Public"]["AED"] = "Public";

$inmodulekey = array_keys($menuFolder, "content");

$z = new __webctrl;
// echo '<pre>';
// print_r($menuFolderModule);
// echo '</pre>';
// echo '<pre>';
// print_r($inmodulekey);
// echo '</pre>';
$pathupload = _RELATIVE_PATH_UPLOAD_;
foreach($inmodulekey as $kModuleKey=>$vModuleKey){
  $LMId = "Admin".$vModuleKey;
  $LMModuleKey = $menuModuleKey[$vModuleKey];
  $dataGroupMathching[$LMId] = $LMModuleKey;
  $arrinkey = array();
  array_push($arrinkey, $LMId, $LMModuleKey);
  $arrOption = $menuOption[$vModuleKey];
  $pathuploadmodule = $pathupload."/".$LMModuleKey."/";
  $pathuploadhtml = $pathuploadmodule."content_htmlfile/";
  $pathuploadfile = $pathuploadmodule."file_attach/";
  $pathuploadgallery = $pathuploadmodule."file_gallery/";
  $pathuploadvdo = $pathuploadmodule."file_vdo/";
  $pathuploadpicture = $pathuploadmodule."thumbnail_picture/";
  $FieldLang = (!empty($_SESSION['Session_Admin_Language'])?$_SESSION['Session_Admin_Language']:'EN');
  $sql = "";
  $sql .= "SELECT "._TABLE_CONTENT_GROUP_."_ID AS ID,"._TABLE_CONTENT_GROUP_."_".$FieldLang." AS Name FROM "._TABLE_CONTENT_GROUP_;
  $sql .= " WHERE "._TABLE_CONTENT_GROUP_."_Folder = '".$LMModuleKey."'";
  $sql .= " AND "._TABLE_CONTENT_GROUP_."_Status = 'On'";
  $sql .= " ORDER BY "._TABLE_CONTENT_GROUP_."_Order DESC";
  $z->sql($sql);
  $RecordCount = $z->num();
  $arrGroup = array();
  if($RecordCount>0){
    $v = $z->row();
    foreach($v as $Row){
      $arr = array();
      $arr["ID"] = $Row["ID"];
      $arr["Name"] = $Row["Name"];
      $arrGroup[] = $arr;
    }
  }
  // $defaultdata[$LMId]["imghome"] = array("W"=>640,"H"=>940,"aspectRatio"=>10/16);
  $defaultdata[$LMId]["imghome"] = array("W"=>1024,"H"=>599,"aspectRatio"=>4/2.5);
  $defaultdata[$LMId]["img"] = array("W"=>265,"H"=>155,"aspectRatio"=>4/2.5);
  $defaultdata[$LMId]["thumb"] = array("P"=>array("thum265","thum840"),"W"=>array(265,840),"H"=>array(155,491));
  $defaultdata[$LMId]["gallery"] = array("W"=>800,"H"=>600);
  $defaultdata[$LMId]["group"] = $arrGroup;//array('A'=>'กิจกรรม','B'=>'กองทุน');
  $defaultdata[$LMId]["filetype"] = ".pdf,.doc,.xls,.ppt,.docx,.xlsx,.pptx,.zip,.jpg,.png";
  $defaultdata[$LMId]["fileupload"] = "index-uploaddocument.php";
  $defaultdata[$LMId]["modulekey"] = $arrinkey;
  $defaultdata[$LMId]["option"] = $arrOption;
  $defaultdata[$LMId]["path"] = array("PATH"=>$pathuploadmodule,"HTML"=>$pathuploadhtml,"FILE"=>$pathuploadfile,"GALLERY"=>$pathuploadgallery,"VDO"=>$pathuploadvdo,"PICTURE"=>$pathuploadpicture);
}
?>
