<?php
$Array_Mod_Lang["txt:Detail Head"]["EN"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["TH"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["CN"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["JP"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["DE"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["FR"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["ES"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["KR"] = "Manage Content system";
$Array_Mod_Lang["txt:Detail Head"]["AED"] = "Manage Content system";

$Array_Mod_Lang["txt:Head 01"]["EN"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["TH"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["CN"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["JP"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["DE"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["FR"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["ES"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["KR"] = "Content Date";
$Array_Mod_Lang["txt:Head 01"]["AED"] = "Content Date";
$Array_Mod_Lang["txt:Head 02"]["EN"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["TH"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["CN"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["JP"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["DE"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["FR"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["ES"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["KR"] = "Content Information";
$Array_Mod_Lang["txt:Head 02"]["AED"] = "Content Information";
$Array_Mod_Lang["txt:Head 03"]["EN"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["TH"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["CN"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["JP"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["DE"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["FR"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["ES"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["KR"] = "Content Address";
$Array_Mod_Lang["txt:Head 03"]["AED"] = "Content Address";
$Array_Mod_Lang["txt:Head 04"]["EN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["TH"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["CN"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["JP"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["DE"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["FR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["ES"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["KR"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 04"]["AED"] = "Content Image Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["EN"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["TH"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["CN"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["JP"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["DE"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["FR"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["ES"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["KR"] = "Content Upload & Preview";
$Array_Mod_Lang["txt:Head 05"]["AED"] = "Content Upload & Preview";

$Array_Mod_Lang["txtinput:inputCountry"]["EN"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["TH"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["CN"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["JP"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["DE"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["FR"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["ES"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["KR"] = "Country";
$Array_Mod_Lang["txtinput:inputCountry"]["AED"] = "Country";

$Array_Mod_Lang["txtinput:inputProvince"]["TH"] = "จังหวัด";
$Array_Mod_Lang["txtinput:inputProvince"]["EN"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["CN"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["JP"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["DE"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["FR"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["ES"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["KR"] = "State/Province";
$Array_Mod_Lang["txtinput:inputProvince"]["AED"] = "State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["TH"] = "เลือกจังหวัด";
$Array_Mod_Lang["txtselect:inputProvince"]["EN"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["CN"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["JP"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["DE"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["FR"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["ES"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["KR"] = "Select State/Province";
$Array_Mod_Lang["txtselect:inputProvince"]["AED"] = "Select State/Province";

$Array_Mod_Lang["txtinput:inputDistrict"]["TH"] = "เขต / อำเภอ";
$Array_Mod_Lang["txtinput:inputDistrict"]["EN"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["CN"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["JP"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["DE"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["FR"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["ES"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["KR"] = "District";
$Array_Mod_Lang["txtinput:inputDistrict"]["AED"] = "District";
$Array_Mod_Lang["txtselect:inputDistrict"]["TH"] = "เลือก เขต / อำเภอ";
$Array_Mod_Lang["txtselect:inputDistrict"]["EN"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["CN"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["JP"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["DE"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["FR"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["ES"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["KR"] = "Select District";
$Array_Mod_Lang["txtselect:inputDistrict"]["AED"] = "Select District";

$Array_Mod_Lang["txtinput:inputZipCode"]["TH"] = "รหัสไปรษณีย์";
$Array_Mod_Lang["txtinput:inputZipCode"]["EN"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["CN"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["JP"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["DE"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["FR"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["ES"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["KR"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputZipCode"]["AED"] = "ZipCode";
$Array_Mod_Lang["txtinput:inputAddress"]["TH"] = "ที่อยู่";
$Array_Mod_Lang["txtinput:inputAddress"]["EN"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["CN"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["JP"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["DE"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["FR"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["ES"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["KR"] = "Address";
$Array_Mod_Lang["txtinput:inputAddress"]["AED"] = "Address";

$Array_Mod_Lang["txtinput:inputEmail"]["TH"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["EN"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["CN"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["JP"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["DE"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["FR"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["ES"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["KR"] = "Email";
$Array_Mod_Lang["txtinput:inputEmail"]["AED"] = "Email";

$Array_Mod_Lang["txtinput:inputTelephone"]["TH"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["EN"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["CN"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["JP"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["DE"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["FR"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["ES"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["KR"] = "Tel";
$Array_Mod_Lang["txtinput:inputTelephone"]["AED"] = "Tel";

$Array_Mod_Lang["txtinput:inputShare_website"]["TH"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["EN"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["CN"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["JP"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["DE"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["FR"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["ES"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["KR"] = "Share Website";
$Array_Mod_Lang["txtinput:inputShare_website"]["AED"] = "Share Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["TH"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["EN"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["CN"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["JP"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["DE"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["FR"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["ES"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["KR"] = "Website";
$Array_Mod_Lang["txtinput:inputWebsite"]["AED"] = "Website";

$Array_Mod_Lang["txtinput:inputGroupTitle"]["EN"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["TH"] = "ชื่อกลุ่ม";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["CN"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["JP"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["DE"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["FR"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["ES"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["KR"] = "Subject Group";
$Array_Mod_Lang["txtinput:inputGroupTitle"]["AED"] = "Subject Group";

$Array_Mod_Lang["txtselect:inputGroupTitle"]["EN"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["TH"] = "เลือกชื่อกลุ่ม";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["CN"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["JP"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["DE"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["FR"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["ES"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["KR"] = "Subject Group";
$Array_Mod_Lang["txtselect:inputGroupTitle"]["AED"] = "Subject Group";

$Array_Mod_Lang["txtinput:inputDesDate"]["EN"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["TH"] = "วันที่เผยแพร่";
$Array_Mod_Lang["txtinput:inputDesDate"]["CN"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["JP"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["DE"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["FR"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["ES"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["KR"] = "Date";
$Array_Mod_Lang["txtinput:inputDesDate"]["AED"] = "Date";
$Array_Mod_Lang["txtinput:inputSubject"]["EN"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["TH"] = "พาดหัว";
$Array_Mod_Lang["txtinput:inputSubject"]["CN"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["JP"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["DE"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["FR"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["ES"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["KR"] = "Subject";
$Array_Mod_Lang["txtinput:inputSubject"]["AED"] = "Subject";
$Array_Mod_Lang["txtinput:inputTitle"]["EN"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["TH"] = "รายละเอียดย่อ";
$Array_Mod_Lang["txtinput:inputTitle"]["CN"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["JP"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["DE"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["FR"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["ES"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["KR"] = "Title";
$Array_Mod_Lang["txtinput:inputTitle"]["AED"] = "Title";
$Array_Mod_Lang["txtinput:inputDetail"]["EN"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["TH"] = "รายละเอียด";
$Array_Mod_Lang["txtinput:inputDetail"]["CN"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["JP"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["DE"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["FR"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["ES"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["KR"] = "Detail";
$Array_Mod_Lang["txtinput:inputDetail"]["AED"] = "Detail";

$Array_Mod_Lang["txtinput:inputTimeZone"]["EN"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["TH"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["CN"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["JP"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["DE"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["FR"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["ES"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["KR"] = "Time Zone";
$Array_Mod_Lang["txtinput:inputTimeZone"]["AED"] = "Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["EN"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["TH"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["CN"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["JP"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["DE"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["FR"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["ES"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["KR"] = "Select Time Zone";
$Array_Mod_Lang["txtselect:inputTimeZone"]["AED"] = "Select Time Zone";

$Array_Mod_Lang["txt:HomeStatus"]["EN"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["TH"] = "หน้าแรก";
$Array_Mod_Lang["txt:HomeStatus"]["CN"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["JP"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["DE"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["FR"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["ES"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["KR"] = "Home";
$Array_Mod_Lang["txt:HomeStatus"]["AED"] = "Home";
$Array_Mod_Lang["txt:Pin"]["EN"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["TH"] = "ปักหมุดของเนื้อหา";
$Array_Mod_Lang["txt:Pin"]["CN"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["JP"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["DE"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["FR"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["ES"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["KR"] = "Pin";
$Array_Mod_Lang["txt:Pin"]["AED"] = "Pin";

$Array_Mod_Lang["txt:Public"]["EN"] = "Public";
$Array_Mod_Lang["txt:Public"]["TH"] = "Public";
$Array_Mod_Lang["txt:Public"]["CN"] = "Public";
$Array_Mod_Lang["txt:Public"]["JP"] = "Public";
$Array_Mod_Lang["txt:Public"]["DE"] = "Public";
$Array_Mod_Lang["txt:Public"]["FR"] = "Public";
$Array_Mod_Lang["txt:Public"]["ES"] = "Public";
$Array_Mod_Lang["txt:Public"]["KR"] = "Public";
$Array_Mod_Lang["txt:Public"]["AED"] = "Public";


$arrinStatusContactBtnClass["TH"]["New"] = "btn-info";
$arrinStatusContactBtnClass["TH"]["Read"] = "btn-alert";
$arrinStatusContactBtnClass["EN"]["New"] = "btn-info";
$arrinStatusContactBtnClass["EN"]["Read"] = "btn-alert";

$arrinContactStatus["TH"]["New"] = "มาใหม่";
$arrinContactStatus["TH"]["Read"] = "อ่านแล้ว";

$arrinContactStatus["EN"]["New"] = "Enable";
$arrinContactStatus["EN"]["Read"] = "Disable";

$z = new __webctrl;
$inmodulekey = array_keys($menuFolder, "supermarket");

$arrGroup = array();
$arr = array();
$arr["ID"] = 1;
$arr["Key"] = "FreshFood";
$arr["Name"] = "Fresh food";
$arrGroup[] = $arr;

$arr = array();
$arr["ID"] = 2;
$arr["Key"] = "DriedFood";
$arr["Name"] = "Dried food";
$arrGroup[] = $arr;

$pathupload = _RELATIVE_PATH_UPLOAD_;
foreach($inmodulekey as $kModuleKey=>$vModuleKey){
	$LMId = "Admin".$vModuleKey;
  $LMModuleKey = $menuModuleKey[$vModuleKey];
  $dataGroupMathching[$LMId] = $LMModuleKey;
  $arrinkey = array();
  array_push($arrinkey, $LMId, $LMModuleKey,'IPicklist');
	$arrOption = $menuOption[$vModuleKey];
	$pathuploadmodule = $pathupload."/".$LMModuleKey."/";
	$pathuploadhtml = $pathuploadmodule."content_htmlfile/";
  $pathuploadfile = $pathuploadmodule."file_attach/";
  $pathuploadgallery = $pathuploadmodule."file_gallery/";
  $pathuploadvdo = $pathuploadmodule."file_vdo/";
  $pathuploadpicture = $pathuploadmodule."thumbnail_picture/";

	$sql = "";
	$sql .= "SELECT "._TABLE_ADMIN_WDAY_."_ID AS ID,"._TABLE_ADMIN_WDAY_."_Name AS Name FROM "._TABLE_ADMIN_WDAY_;
	$sql .= " ORDER BY "._TABLE_ADMIN_WDAY_."_ID ASC";
	$z->sql($sql);
	$RecordCount = $z->num();
	$arrDay = array();
	if($RecordCount>0){
		$v = $z->row();
		foreach($v as $Row){
			$arr = array();
			$arr["ID"] = $Row["ID"];
			$arr["Name"] = $Row["Name"];
			$arrDay[] = $arr;
			unset($arr);
		}
	}

	$defaultdata[$LMId]["imghome"] = array("W"=>1024,"H"=>768,"aspectRatio"=>4/2.5);
  $defaultdata[$LMId]["img"] = array("W"=>1250,"H"=>425,"aspectRatio"=>4/1.36);
  $defaultdata[$LMId]["thumb"] = array("P"=>array("thum300","thum800"),"W"=>array(300,800),"H"=>array(102,272));
	$defaultdata[$LMId]["gallery"] = array("W"=>800,"H"=>600);
  $defaultdata[$LMId]["group"] = $arrGroup;//array('A'=>'กิจกรรม','B'=>'กองทุน');
	$defaultdata[$LMId]["day"] = $arrDay;
  $defaultdata[$LMId]["filetype"] = ".pdf,.doc,.xls,.ppt,.docx,.xlsx,.pptx,.zip,.jpg,.png";
  $defaultdata[$LMId]["fileupload"] = "index-uploaddocument.php";
  $defaultdata[$LMId]["modulekey"] = $arrinkey;
  $defaultdata[$LMId]["option"] = $arrOption;
  $defaultdata[$LMId]["path"] = array("PATH"=>$pathuploadmodule,"HTML"=>$pathuploadhtml,"FILE"=>$pathuploadfile,"GALLERY"=>$pathuploadgallery,"VDO"=>$pathuploadvdo,"PICTURE"=>$pathuploadpicture);
}
?>
