<?php
$indexmaingroup = 1;
$MenuGroupMain[$indexmaingroup] = $indexmaingroup;
$MenuGroupMainName[$indexmaingroup] = "System";

$indexgroupmenu = 1;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Administrator";
$MenuGroupIcon[$indexgroupmenu] = "fa-laptop";

$indexmenu = 1;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Employee";
$menuFolder[$indexmenu]="employee";
$menuLink[$indexmenu]="../employee/index.php";
$menuFolderModule[$indexmenu]="employee";
$menuModuleKey[$indexmenu]="employee";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="EmpCode";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-user";

$indexmenu = 2;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="User Management";
$menuFolder[$indexmenu]="user_management";
$menuLink[$indexmenu]="../useradmin/index.php";
$menuFolderModule[$indexmenu]="user_management";
$menuModuleKey[$indexmenu]="user_management";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ID";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-user-plus";

$indexmenu = 3;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Group Management";
$menuFolder[$indexmenu]="groupuser";
$menuLink[$indexmenu]="../groupuser/index.php";
$menuFolderModule[$indexmenu]="groupuser";
$menuModuleKey[$indexmenu]="groupuser";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ID";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-users";

$indexgroupmenu = 2;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Management (CMS)";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 4;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Banner";
$menuFolder[$indexmenu]="banner";
$menuLink[$indexmenu]="../banner/index.php";
$menuFolderModule[$indexmenu]="banner";
$menuModuleKey[$indexmenu]="banner";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";

/*
$indexmenu = 5;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Weblink";
$menuFolder[$indexmenu]="weblink";
$menuLink[$indexmenu]="../weblink/index.php";
$menuFolderModule[$indexmenu]="weblink";
$menuModuleKey[$indexmenu]="weblink";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";
*/

$indexmenu = 6;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Floating Ad.";
$menuFolder[$indexmenu]="ads";
$menuLink[$indexmenu] = "../floating/index.php";
$menuFolderModule[$indexmenu]="floating";
$menuModuleKey[$indexmenu]="floating";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";

$indexmenu = 7;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Intro page";
$menuFolder[$indexmenu]="intropage";
$menuLink[$indexmenu]="../intropage/index.php";
$menuFolderModule[$indexmenu]="intropage";
$menuModuleKey[$indexmenu]="intro";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";

$indexmenu = 8;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Stock Images / File";
$menuFolder[$indexmenu]="managefile";
$menuLink[$indexmenu]="../managefile/imgcard.php";
$menuFolderModule[$indexmenu]="managefile";
$menuModuleKey[$indexmenu]="managefile";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 9;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="About";
$menuFolder[$indexmenu]="about";
$menuLink[$indexmenu]="../about/index.php";
$menuFolderModule[$indexmenu]="about";
$menuModuleKey[$indexmenu]="about";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListCount";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";

$indexmenu = 10;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="News Management";
$menuFolder[$indexmenu]="content";
$menuLink[$indexmenu]="../content/index.php";
$menuFolderModule[$indexmenu]="content";
$menuModuleKey[$indexmenu]="cms";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

/*
$indexmenu = 11;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Gallery";
$menuFolder[$indexmenu]="content";
$menuLink[$indexmenu]="../content/index.php";
$menuFolderModule[$indexmenu]="content";
$menuModuleKey[$indexmenu]="gallery";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";
*/

$indexmenu = 12;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Video";
$menuFolder[$indexmenu]="contentvdo";
$menuLink[$indexmenu]="../contentvdo/index.php";
$menuFolderModule[$indexmenu]="contentvdo";
$menuModuleKey[$indexmenu]="vdo";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

/*
$indexmenu = 13;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Download";
$menuFolder[$indexmenu]="contentdownload";
$menuLink[$indexmenu]="../contentdownload/index.php";
$menuFolderModule[$indexmenu]="contentdownload";
$menuModuleKey[$indexmenu]="download";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";
*/

$indexmenu = 14;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="ติดต่อสอบถาม";
$menuFolder[$indexmenu]="contactus";
$menuLink[$indexmenu]="../contactus/group.php";
$menuFolderModule[$indexmenu]="contactus";
$menuModuleKey[$indexmenu]="contactus";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

$indexmenu = 15;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Group Content";
$menuFolder[$indexmenu]="groupcontent";
$menuLink[$indexmenu]="../groupcontent/index.php";
$menuFolderModule[$indexmenu]="groupcontent";
$menuModuleKey[$indexmenu]="groupcontent";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

/*
$indexmenu = 16;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Group Download";
$menuFolder[$indexmenu]="groupdownload";
$menuLink[$indexmenu]="../groupdownload/index.php";
$menuFolderModule[$indexmenu]="groupdownload";
$menuModuleKey[$indexmenu]="groupdownload";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";
*/

$indexmenu = 17;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Group VDO";
$menuFolder[$indexmenu]="groupvdo";
$menuLink[$indexmenu]="../groupvdo/index.php";
$menuFolderModule[$indexmenu]="groupvdo";
$menuModuleKey[$indexmenu]="groupvdo";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

/*
$indexmenu = 18;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Group Weblink";
$menuFolder[$indexmenu]="groupweblink";
$menuLink[$indexmenu]="../groupweblink/index.php";
$menuFolderModule[$indexmenu]="groupweblink";
$menuModuleKey[$indexmenu]="groupweblink";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";
*/

$indexgroupmenu = 3;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Ingredients";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 19;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Ingredient Picklist";
$menuFolder[$indexmenu]="ingredients";
$menuLink[$indexmenu]="../ingredients/group.php";
$menuFolderModule[$indexmenu]="ingredients";
$menuModuleKey[$indexmenu]="IPicklist";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 20;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Ingredient listing";
$menuFolder[$indexmenu]="ingredients";
$menuLink[$indexmenu]="../ingredients/index.php";
$menuFolderModule[$indexmenu]="ingredients";
$menuModuleKey[$indexmenu]="IList";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 4;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Supermarket";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 21;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Supermarket Listing";
$menuFolder[$indexmenu]="supermarket";
$menuLink[$indexmenu]="../supermarket/index.php";
$menuFolderModule[$indexmenu]="supermarket";
$menuModuleKey[$indexmenu]="SupermarketListing";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 5;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Thaitrade Center";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 22;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Royal thai embassy listing";
$menuFolder[$indexmenu]="thaiembassy";
$menuLink[$indexmenu]="../thaiembassy/index.php";
$menuFolderModule[$indexmenu]="thaiembassy";
$menuModuleKey[$indexmenu]="RoyalThaiEmbassyListing";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 34;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Pending restaurant";
$menuFolder[$indexmenu]="thaiembassy";
$menuLink[$indexmenu]="../thaiembassy/pending.php";
$menuFolderModule[$indexmenu]="pendingrestaurant";
$menuModuleKey[$indexmenu]="Pendingrestaurant";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 6;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Blog Management";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 23;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Blog Category";
$menuFolder[$indexmenu]="blog";
$menuLink[$indexmenu]="../blog/group.php";
$menuFolderModule[$indexmenu]="blog";
$menuModuleKey[$indexmenu]="BlogtGroup";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 24;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Blog List";
$menuFolder[$indexmenu]="blog";
$menuLink[$indexmenu]="../blog/index.php";
$menuFolderModule[$indexmenu]="blog";
$menuModuleKey[$indexmenu]="BlogtListing";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 25;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Blog Setting";
$menuFolder[$indexmenu]="groupcontent";
$menuLink[$indexmenu]="../groupcontent/index.php";
$menuFolderModule[$indexmenu]="groupcontent";
$menuModuleKey[$indexmenu]="groupcontent";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="Code";
$menuDefaultOrder[$indexmenu]="ASC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 7;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "FAQ Management";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 26;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="FAQ listing";
$menuFolder[$indexmenu]="faq";
$menuLink[$indexmenu]="../faq/index.php";
$menuFolderModule[$indexmenu]="faq";
$menuModuleKey[$indexmenu]="FAQListing";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 8;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Recipes";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 27;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Recipes Picklist";
$menuFolder[$indexmenu]="recipes";
$menuLink[$indexmenu]="../recipes/group.php";
$menuFolderModule[$indexmenu]="recipes";
$menuModuleKey[$indexmenu]="RecipestPicklist";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexmenu = 28;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Recipes listing";
$menuFolder[$indexmenu]="recipes";
$menuLink[$indexmenu]="../recipes/index.php";
$menuFolderModule[$indexmenu]="recipes";
$menuModuleKey[$indexmenu]="RecipestListing";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-picture-o";

$indexgroupmenu = 9;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Member Management";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 29;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="Member";
$menuFolder[$indexmenu]="member";
$menuLink[$indexmenu]="../member/index.php";
$menuFolderModule[$indexmenu]="member";
$menuModuleKey[$indexmenu]="member";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-comments";

$indexgroupmenu = 10;
$MenuMainGroup[$indexgroupmenu] = $indexmaingroup;
$MenuGroup[$indexgroupmenu] = $indexgroupmenu;
$MenuGroupName[$indexgroupmenu] = "Newsletter";
$MenuGroupIcon[$indexgroupmenu] = "fa-cogs";

$indexmenu = 30;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="E-newsletter - สมุดที่อยู่";
$menuFolder[$indexmenu]="enew";
$menuLink[$indexmenu]="../enew/index.php";
$menuFolderModule[$indexmenu]="enew";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

$indexmenu = 31;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="E-newsletter - กลุ่ม";
$menuFolder[$indexmenu]="enew";
$menuLink[$indexmenu]="../enew/group.php";
$menuFolderModule[$indexmenu]="enew";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

$indexmenu = 32;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="E-newsletter - เอกสาร";
$menuFolder[$indexmenu]="enew";
$menuLink[$indexmenu]="../enew/doc.php";
$menuFolderModule[$indexmenu]="enew";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";

$indexmenu = 33;
$menuIndex[$indexmenu]="Admin".$indexmenu;
$menuName[$indexmenu]="E-newsletter - งานที่ส่ง";
$menuFolder[$indexmenu]="enew";
$menuLink[$indexmenu]="../enew/task.php";
$menuFolderModule[$indexmenu]="enew";
$menuOption[$indexmenu]="0";
$menuInGroup[$indexmenu]=$indexgroupmenu;
$menuType[$indexmenu]="module";//module,link
$menuTarget[$indexmenu]="_self";
$menuDefaultList[$indexmenu]="ListOrder";
$menuDefaultOrder[$indexmenu]="DESC";
$menuDefaultFilter[$indexmenu]="";
$menuDefaultStatus[$indexmenu]="";
$menuDefaultDetails[$indexmenu]="";
$menuDefaultIcon[$indexmenu]="fa-gears";


?>
